name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            arch: AMD64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            arch: Intel
          - os: macos-latest
            goos: darwin
            goarch: arm64
            arch: ARM
          - os: windows-latest
            goos: windows
            goarch: amd64
            arch: AMD64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # important for git tags fetching

      - name: Setup Environment Variables and Git Tag Versioning
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*  # Fetch only the needed tags
          GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV


      - name: Get dependencies
        run: go mod tidy

      - name: Build
        run: go build -v -ldflags="-X main.version=${{ env.GIT_TAG }}" -o hyphen-${{ matrix.arch }}
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: hyphen-${{ matrix.os }}-${{ matrix.arch }}-${{ env.GIT_TAG }}
          path: hyphen-${{ matrix.arch }}
