name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            arch: AMD64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            arch: Intel
          - os: macos-latest
            goos: darwin
            goarch: arm64
            arch: ARM
          - os: windows-latest
            goos: windows
            goarch: amd64
            arch: AMD64

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Set environment variables
        run: |
          echo "GOOS=${{ matrix.goos }}" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.goarch }}" >> $GITHUB_ENV

      - name: Build
        run: go build -v -o myapp-${{ matrix.arch }}
        shell: bash  

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.os }}-${{ matrix.arch }}
          path: myapp-${{ matrix.arch }}
