name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  get-latest-release:
    name: Get Latest Release
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_latest_release.outputs.release_tag }}
    steps:
      - name: Get Latest Release
        id: get_latest_release
        uses: actions/github-script@v7
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return latestRelease.data.tag_name;
      - name: Set output
        id: set_output
        run: echo "release_tag=${{ steps.get_latest_release.outputs.result }}" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: [test, get-latest-release]
    uses: ./.github/workflows/build.yml
    with:
      latest_release: ${{ needs.get-latest-release.outputs.release_tag }}
    secrets: inherit


  upload-dev:
    name: Upload to R2
    needs: [build, get-latest-release]
    if: github.event_name == 'push' && contains(github.ref, '.')
    uses: ./.github/workflows/upload-to-r2-dev.yml
    with:
      latest_release: ${{ needs.get-latest-release.outputs.release_tag }}
    secrets: inherit
