name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # - name: Check out code
      #   uses: actions/checkout@v3
      #
      # - name: Cache Go modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      # - name: Test with Coverage
      #   run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      #
      # - name: Upload Coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     file: ./coverage.txt

  release:
    name: Release
    needs: test
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install semantic-release
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog

      - name: Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTPUT=$(npx semantic-release --dry-run --no-ci)
          if echo "$OUTPUT" | grep -q "There are no relevant changes, so no new version is released."; then
            echo "No new release"
            echo "new_release_version=" >> $GITHUB_OUTPUT
          else
            VERSION=$(echo "$OUTPUT" | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+(-rc\.[0-9]+)?')
            if [ -n "$VERSION" ]; then
              echo "New version: $VERSION"
              echo "new_release_version=$VERSION" >> $GITHUB_OUTPUT
              npx semantic-release
            else
              echo "Could not determine version"
              echo "new_release_version=" >> $GITHUB_OUTPUT
            fi
          fi

  build:
    name: Build
    needs: release
    if: needs.release.outputs.new_release_version != ''
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.release.outputs.new_release_version }}
    secrets: inherit

  upload-dev:
    name: Upload to R2
    needs: [release, build]
    if: needs.release.outputs.new_release_version != ''
    uses: ./.github/workflows/upload-to-r2-dev.yml
    with:
      version: ${{ needs.release.outputs.new_release_version }}
    secrets: inherit
