name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    needs: test

  upload:
    name: Upload to R2
    needs: build
    if: github.event_name == 'push' && contains(github.ref, '.')
    uses: ./.github/workflows/upload-to-r2.yml
    with:
      git_tag: ${{ github.ref_name }}
    secrets: inherit

  mock-upload:
    name: Mock Upload to R2
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Mock R2 Upload
        run: |
          echo "Mocking R2 upload process"
          for artifact in hyphen-*; do
            echo "Would upload $artifact to s3://cdn-hyphen-ai/hyphen-cli/PR-${{ github.event.pull_request.number }}/$artifact"
          done

      - name: Validate artifacts
        run: |
          for artifact in hyphen-*; do
            if [[ ! -f "$artifact" ]]; then
              echo "Error: Artifact $artifact not found"
              exit 1
            fi
            echo "Artifact $artifact is valid"
          done
