name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  version-bump:
    name: Update Version Based on Conventional Commits
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      new_version: ${{ steps.update_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get latest release and bump status
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              const latestRelease = releases.data[0];
              if (!latestRelease) {
                return { version: '0.0.0', bumpStatus: 'not_bumped' };
              }
              const version = latestRelease.tag_name.replace('v', '');
              const bumpStatus = latestRelease.body.includes('BUMP_STATUS: bumped') ? 'bumped' : 'not_bumped';
              return { version, bumpStatus };
            } catch (e) {
              console.error(e);
              return { version: '0.0.0', bumpStatus: 'not_bumped' };
            }

      - name: Determine version bump
        id: version_bump
        run: |
          latest_version="${{ fromJson(steps.get_latest_release.outputs.result).version }}"
          bump_status="${{ fromJson(steps.get_latest_release.outputs.result).bumpStatus }}"
          echo "Latest version: $latest_version"
          echo "Current bump status: $bump_status"
          
          commits=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s")
          
          bump_type="none"
          if [[ $latest_version != *"-rc."* && $bump_status == "not_bumped" ]]; then
            if echo "$commits" | grep -qE '^BREAKING CHANGE:' || echo "$commits" | grep -qE '^[^:]+!:'; then
              bump_type="major"
            elif echo "$commits" | grep -qE '^feat(\(.+\))?:'; then
              bump_type="minor"
            elif echo "$commits" | grep -qE '^fix(\(.+\))?:'; then
              bump_type="patch"
            fi
          fi
          
          echo "Determined bump type: $bump_type"
          echo "bump_type=${bump_type}" >> $GITHUB_OUTPUT

      - name: Update version
        id: update_version
        run: |
          version="${{ fromJson(steps.get_latest_release.outputs.result).version }}"
          bump_type=${{ steps.version_bump.outputs.bump_type }}
          
          if [[ $version == *"-rc."* ]]; then
            IFS='-' read -ra ADDR <<< "$version"
            base_version="${ADDR[0]}"
            rc_version="${ADDR[1]}"
            rc_number="${rc_version#rc.}"
            new_rc_number=$((rc_number + 1))
            new_version="${base_version}-rc.${new_rc_number}"
          else
            IFS='.' read -ra VER <<< "$version"
            if [[ $bump_type == "major" ]]; then
              new_version="$((${VER[0]} + 1)).0.0-rc.1"
            elif [[ $bump_type == "minor" ]]; then
              new_version="${VER[0]}.$((${VER[1]} + 1)).0-rc.1"
            elif [[ $bump_type == "patch" ]]; then
              new_version="${VER[0]}.${VER[1]}.$((${VER[2]} + 1))-rc.1"
            else
              new_version="${version}-rc.1"
            fi
          fi
          
          echo "New version: $new_version"
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      - name: Create or update RC release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { new_version } = process.env;
            const bumpStatus = '${{ steps.version_bump.outputs.bump_type }}' !== 'none' ? 'bumped' : 'not_bumped';
            
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const rcRelease = releases.data.find(release => release.tag_name.includes('-rc.'));
              
              const releaseBody = `This is the latest release candidate.
              Version: ${new_version}
              Commit: ${context.sha}
              BUMP_STATUS: ${bumpStatus}`;
                        
              if (rcRelease) {
                console.log(`Updating existing RC release: ${rcRelease.tag_name} to ${new_version}`);
                await github.rest.repos.updateRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: rcRelease.id,
                  tag_name: `v${new_version}`,
                  name: `Release Candidate ${new_version}`,
                  body: releaseBody,
                  prerelease: true
                });
              } else {
                console.log(`Creating new RC release: ${new_version}`);
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: `v${new_version}`,
                  name: `Release Candidate ${new_version}`,
                  body: releaseBody,
                  prerelease: true
                });
              }
            } catch (error) {
              console.error('Error updating or creating RC release:', error);
              throw error;
            }
        env:
          new_version: ${{ steps.update_version.outputs.new_version }}

  build:
    name: Build
    needs: [test, version-bump]
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version-bump.outputs.new_version }}
    secrets: inherit

  upload-dev:
    name: Upload to R2
    needs: [build, version-bump]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/upload-to-r2-dev.yml
    with:
      version: ${{ needs.version-bump.outputs.new_version }}
    secrets: inherit
