name: Go CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test with Coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  version-bump:
    name: Update Release Candidate Version
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    outputs:
      new_version: ${{ steps.update_rc_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              const latestRelease = releases.data[0];
              return latestRelease ? latestRelease.tag_name.replace('v', '') : '0.0.0';
            } catch (e) {
              console.error(e);
              return '0.0.0';
            }

      - name: Update RC version
        id: update_rc_version
        run: |
          version=${{ steps.get_latest_release.outputs.result }}
          echo "Current version: $version"
          
          if [[ $version == *"-rc."* ]]; then
            IFS='-' read -ra ADDR <<< "$version"
            base_version="${ADDR[0]}"
            rc_version="${ADDR[1]}"
            rc_number="${rc_version#rc.}"
            new_rc_number=$((rc_number + 1))
            new_version="${base_version}-rc.${new_rc_number}"
          else
            IFS='.' read -ra ADDR <<< "$version"
            new_version="${ADDR[0]}.${ADDR[1]}.$((${ADDR[2]} + 1))-rc.1"
          fi
          
          echo "New version: $new_version"
          echo "new_version=${new_version}" >> $GITHUB_OUTPUT

      - name: Create or update RC release
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const { new_version } = process.env;
            
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const rcRelease = releases.data.find(release => release.tag_name.includes('-rc.'));
              
              if (rcRelease) {
                console.log(`Updating existing RC release: ${rcRelease.tag_name} to ${new_version}`);
                await github.rest.repos.updateRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: rcRelease.id,
                  tag_name: `v${new_version}`,
                  name: `Release Candidate ${new_version}`,
                  body: `This is the latest release candidate.\n\nVersion: ${new_version}\nCommit: ${context.sha}`,
                  prerelease: true
                });
              } else {
                console.log(`Creating new RC release: ${new_version}`);
                await github.rest.repos.createRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  tag_name: `v${new_version}`,
                  name: `Release Candidate ${new_version}`,
                  body: `This is the latest release candidate.\n\nVersion: ${new_version}\nCommit: ${context.sha}`,
                  prerelease: true
                });
              }
            } catch (error) {
              console.error('Error updating or creating RC release:', error);
              throw error;
            }
        env:
          new_version: ${{ steps.update_rc_version.outputs.new_version }}

  build:
    name: Build
    needs: [test, version-bump]
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version-bump.outputs.new_version }}
    secrets: inherit

  upload-dev:
    name: Upload to R2
    needs: [build, version-bump]
    uses: ./.github/workflows/upload-to-r2-dev.yml
    with:
      version: ${{ needs.version-bump.outputs.new_version }}
    secrets: inherit
