name: Deployment to Prod

on:
  release:
    types:
      - published

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Extract version without 'v' prefix
        id: get_version
        run: echo "version=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT

  build:
    needs: extract-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}

  upload:
    needs: [extract-version, build]
    uses: ./.github/workflows/upload-pacakge-to-r2.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
      package_name: hyphen-cli
    secrets: inherit
