name: Publish to Chocolatey

on:
  release:
    types:
      - published

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Extract version without 'v' prefix
        id: get_version
        run: echo "version=$(echo ${{ github.ref_name }} | sed 's/^v//')" >> $GITHUB_OUTPUT

  publish-to-chocolatey:
    needs: extract-version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Chocolatey
        uses: chocolatey/setup-chocolatey@v1
        
      - name: Set Chocolatey API key
        run: choco apikey --key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/
        
      - name: Update nuspec version
        run: |
          $version = "${{ needs.extract-version.outputs.version }}"
          (Get-Content .\hyphen.nuspec) -replace '\$version\$', $version | Set-Content .\hyphen.nuspec

      - name: Download CLI executable
        run: |
          $version = "${{ needs.extract-version.outputs.version }}"
          $url = "https://api.hyphen.ai/api/downloads/hyphen-cli/$version?os=windows"
          Invoke-WebRequest -Uri $url -OutFile .\tools\hyphen.exe

      - name: Calculate checksum
        run: |
          $checksum = (Get-FileHash -Path .\tools\hyphen.exe -Algorithm SHA256).Hash.ToLower()
          (Get-Content .\tools\chocolateyinstall.ps1) -replace "checksum\s*=\s*''", "checksum = '$checksum'" | Set-Content .\tools\chocolateyinstall.ps1

      - name: Pack Chocolatey package
        run: |
          $version = "${{ needs.extract-version.outputs.version }}"
          choco pack --version $version

      - name: Push to Chocolatey
        run: |
          $version = "${{ needs.extract-version.outputs.version }}"
          choco push hyphen.$version.nupkg --source https://push.chocolatey.org/
