name: Upload to R2

on:
  workflow_call:
    inputs:
      git_tag:
        required: true
        type: string

env:
  CDN_R2_ACCOUNT_ID: e5146df3269d748421cee3ff9d6fa02a
  CDN_R2_ACCESS_KEY_ID: ${{ secrets.CDN_R2_ACCESS_KEY_ID }}
  CDN_R2_SECRET_ACCESS_KEY: ${{ secrets.CDN_R2_SECRET_ACCESS_KEY }}
  CDN_R2_PUBLIC_BASE_URL: https://cdn.hyphen.ai
  CDN_STORAGE_BUCKET_NAME: cdn-hyphen-ai

jobs:
  upload:
    name: Upload artifacts to R2
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Configure AWS CLI for R2
        run: |
          aws configure set aws_access_key_id ${{ env.CDN_R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.CDN_R2_SECRET_ACCESS_KEY }}
          aws configure set region auto
          aws configure set endpoint-url https://${{ env.CDN_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com

      - name: Upload artifacts to R2
        run: |
          for artifact in hyphen-*; do
            aws s3 cp $artifact s3://${{ env.CDN_STORAGE_BUCKET_NAME }}/hyphen-cli/${{ inputs.git_tag }}/$artifact
          done
