name: Upload Install Scripts to R2

on:
  push:
    branches:
      - main
    paths:
      - 'install.sh'
      - 'install.ps1'
  workflow_dispatch:

env:
  CDN_R2_ACCOUNT_ID: e5146df3269d748421cee3ff9d6fa02a
  CDN_R2_ACCESS_KEY_ID: ${{ secrets.CDN_R2_ACCESS_KEY_ID }}
  CDN_R2_SECRET_ACCESS_KEY: ${{ secrets.CDN_R2_SECRET_ACCESS_KEY }}
  CDN_STORAGE_BUCKET_NAME: cdn-hyphen-ai

jobs:
  upload-install-scripts:
    name: Upload Install Scripts
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ env.CDN_R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.CDN_R2_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Upload install.sh to R2
        run: |
          if [ -f install.sh ]; then
            aws s3 cp install.sh s3://${{ env.CDN_STORAGE_BUCKET_NAME }}/install/install.sh \
              --endpoint-url https://${{ env.CDN_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            echo "Uploaded install.sh"
          else
            echo "install.sh not found, skipping upload"
          fi

      - name: Upload install.ps1 to R2
        run: |
          if [ -f install.ps1 ]; then
            aws s3 cp install.ps1 s3://${{ env.CDN_STORAGE_BUCKET_NAME }}/install/install.ps1 \
              --endpoint-url https://${{ env.CDN_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
            echo "Uploaded install.ps1"
          else
            echo "install.ps1 not found, skipping upload"
          fi

      - name: Verify uploads
        run: |
          echo "Verifying uploaded files:"
          for file in install.sh install.ps1; do
            if aws s3 ls "s3://${{ env.CDN_STORAGE_BUCKET_NAME }}/install/$file" \
              --endpoint-url https://${{ env.CDN_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com; then
              echo "Verified: install/$file"
            else
              echo "Warning: File not found in R2: install/$file"
            fi
          done

